version: '3.8'
services:
  vectordb:
    image: vectordb/vectordb:latest
    ports:
      - "5000:5000"
    environment:
      VECTOR_DB_PASSWORD: "pw"
    volumes:
      - vectordb_data:/var/lib/vectordb

volumes:
  vectordb_data:
